/* @flow */

export const TRANSACTION_STATUS = {

    // Transaction has been created. The buyer has clicked on a button,
    // and an account has been created, but the client is not yet listening
    // for transfers
    CREATED:  'created',

    // We are waiting for buyer to send funds into the account matching or
    // exceeding the amount of the transaction
    WAITING:  'waiting',

    // The buyer has not sent funds in time and the transaction has expired
    EXPIRED:  'expired',

    // The transaction has been refunded, if any balance was sent late. Transactions
    // with this status will still be monitored for payments for 100 minutes.
    REFUNDED: 'refunded',

    // The payment has been made, the funds are pending in the account, and the buyer
    // has proceeded on the merchant's page -- but the processing / PoW has not yet happened
    // on the BrainBlocks side for the send/recieve blocks
    PENDING:  'pending',
    
    // The transaction has been fully processed. We will wait 100 minutes for any subsequent
    // payments that we might need to refund.
    COMPLETE: 'complete',

    // The transaction has been fully processed. We will wait 100 minutes for any subsequent
    // payments that we might need to refund.
    FORCE: 'force',

    // The transaction has been purged. We will not wait for any more activity on this account
    PURGED:   'purged',

    // There was an error processing the transaction
    ERROR: 'error'
};

// Happy case: CREATED -> WAITING -> PENDING -> COMPLETE
// Unhappy case: CREATED -> WAITING -> EXPIRED -> REFUNDED -> PURGED

export const CURRENCY = {
    NANO: 'nano',
    BTC:  'btc',
    BCH:  'bch',
    USD:  'usd',
    EUR:  'eur',
    GBP:  'gbp',
    JPY:  'jpy',
    CAD:  'cad',
    AUD:  'aud',
    CNY:  'cny',
    CHF:  'chf',
    SEK:  'sek',
    NZD:  'nzd',
    KRW:  'krw',
    AED:  'aed',
    AFN:  'afn',
    ALL:  'all',
    AMD:  'amd',
    ANG:  'ang',
    AOA:  'aoa',
    ARS:  'ars',
    AWG:  'awg',
    AZN:  'azn',
    BAM:  'bam',
    BBD:  'bbd',
    BDT:  'bdt',
    BGN:  'bgn',
    BHD:  'bhd',
    BIF:  'bif',
    BMD:  'bmd',
    BND:  'bnd',
    BOB:  'bob',
    BRL:  'brl',
    BSD:  'bsd',
    BTN:  'btn',
    BWP:  'bwp',
    BZD:  'bzd',
    CDF:  'cdf',
    CLF:  'clf',
    CLP:  'clp',
    COP:  'cop',
    CRC:  'crc',
    CUP:  'cup',
    CVE:  'cve',
    CZK:  'czk',
    DJF:  'djf',
    DKK:  'dkk',
    DOP:  'dop',
    DZD:  'dzd',
    EGP:  'egp',
    ETB:  'etb',
    FJD:  'fjd',
    FKP:  'fkp',
    GEL:  'gel',
    GHS:  'ghs',
    GIP:  'gip',
    GMD:  'gmd',
    GNF:  'gnf',
    GTQ:  'gtq',
    GYD:  'gyd',
    HKD:  'hkd',
    HNL:  'hnl',
    HRK:  'hrk',
    HTG:  'htg',
    HUF:  'huf',
    IDR:  'idr',
    ILS:  'ils',
    INR:  'inr',
    IQD:  'iqd',
    IRR:  'irr',
    ISK:  'isk',
    JEP:  'jep',
    JMD:  'jmd',
    JOD:  'jod',
    KES:  'kes',
    KGS:  'kgs',
    KHR:  'khr',
    KMF:  'kmf',
    KPW:  'kpw',
    KWD:  'kwd',
    KYD:  'kyd',
    KZT:  'kzt',
    LAK:  'lak',
    LBP:  'lbp',
    LKR:  'lkr',
    LRD:  'lrd',
    LSL:  'lsl',
    LYD:  'lyd',
    MAD:  'mad',
    MDL:  'mdl',
    MGA:  'mga',
    MKD:  'mkd',
    MMK:  'mmk',
    MNT:  'mnt',
    MOP:  'mop',
    MRU:  'mru',
    MUR:  'mur',
    MVR:  'mvr',
    MWK:  'mwk',
    MXN:  'mxn',
    MYR:  'myr',
    MZN:  'mzn',
    NAD:  'nad',
    NGN:  'ngn',
    NIO:  'nio',
    NOK:  'nok',
    NPR:  'npr',
    OMR:  'omr',
    PAB:  'pab',
    PEN:  'pen',
    PGK:  'pgk',
    PHP:  'php',
    PKR:  'pkr',
    PLN:  'pln',
    PYG:  'pyg',
    QAR:  'qar',
    RON:  'ron',
    RSD:  'rsd',
    RUB:  'rub',
    RWF:  'rwf',
    SAR:  'sar',
    SBD:  'sbd',
    SCR:  'scr',
    SDG:  'sdg',
    SGD:  'sgd',
    SHP:  'shp',
    SLL:  'sll',
    SOS:  'sos',
    SRD:  'srd',
    STN:  'stn',
    SVC:  'svc',
    SYP:  'syp',
    SZL:  'szl',
    THB:  'thb',
    TJS:  'tjs',
    TMT:  'tmt',
    TND:  'tnd',
    TOP:  'top',
    TRY:  'try',
    TTD:  'ttd',
    TWD:  'twd',
    TZS:  'tzs',
    UAH:  'uah',
    UGX:  'ugx',
    UYU:  'uyu',
    UZS:  'uzs',
    VEF:  'vef',
    VES:  'ves',
    VND:  'vnd',
    VUV:  'vuv',
    WST:  'wst',
    XAF:  'xaf',
    XCD:  'xcd',
    XOF:  'xof',
    XPF:  'xpf',
    YER:  'yer',
    ZAR:  'zar',
    ZMW:  'zmw',
    ZWL:  'zwl',
    XAG:  'xag',
    XAU:  'xau'
};
